<a href="https://colab.research.google.com/github/midhatkamal5/PythonBasics/blob/main/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Machine Learning")

Machine Learning


**Checking Value of X**

In [ ]:
x = 5
if x > 10:
  print("x is greater than 10")
else:
  print("x is less than 10")

x is less than 10


In [ ]:
name = "Midhat"

In [ ]:
rate=7
name="Bat"
price=9.76
category='H'
isAvailable=True


print(type(rate))
print(type(name))
print(type(price))
print(type(category))
print(type(isAvailable))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [ ]:
print(f"Product Name: {name} ;Product Price: {price}; Product Rate: {rate}") #f is used for formatting

Product Name: Bat ;Product Price: 9.76; Product Rate: 7


In [ ]:
#Type casting -> str()
# int()
# float()
# bool()
print(f"Int Price is: {int(price)}")


Round of Price is: 9


In [ ]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))

age = age + 1
print(f"Hello {name}")
print(f"You are {age} years old")


Enter your name: Midhat
Enter your age: 25
Hello Midhat
You are 26 years old


## **Rectangle Area Calculation**

In [ ]:
#Rectangle Area Calculation
width = float(input("Please enter the width: "))
height = float(input("Please enter the height: "))
print(f"The area is: {width*height}")

Please enter the width: 5.5
Please enter the height: 5.5
The area is: 30.25


## **Shopping Cart Program**

In [ ]:
#Shopping Cart Program
productName =  "Bat"
unitPrice = 102.56
quantity = int(input("Please enter the quantity of Bat: "))
print(f"Product Name: {productName}")
print(f"Unit Price: Rs.{unitPrice}")
print(f"Price: Rs.{quantity*unitPrice}")

Please enter the quantity of Bat: 5
Product Name: Bat
Unit Price: Rs.102.56
Price: Rs.512.8


In [ ]:
#Indexing
creditCardNumber = "1234-5678-9012-6354"
print(creditCardNumber[0])
print(creditCardNumber[5:9])
print(creditCardNumber[:9])
print(creditCardNumber[9:])
print(creditCardNumber[::2]) #go from start to end by skipping 2 (step size)

#reverse indexing
print(creditCardNumber[-1])


1
5678
1234-5678
-9012-6354
13-6891-34
4


In [ ]:
arr = []
encryptedStr="";
creditCardNumberInput = input("Enter the card number: ")
tobeencrypted = creditCardNumberInput[0:len(creditCardNumberInput)-4]
print(f"{tobeencrypted}")
for x in range(len(tobeencrypted)):
  if tobeencrypted[x] == "-":
    encryptedStr += '-'
  else:
    encryptedStr += 'X'
lastdigits = creditCardNumberInput[-4:]
print(f"Your credit card last digits are: {encryptedStr}{lastdigits}")


Enter the card number: 1234-5678-9012-6354
1234-5678-9012-
Your credit card last digits are: XXXX-XXXX-XXXX-6354


## **String Methods**

In [ ]:
x = "Hello Customer! Your credit card number is 1234-5678-9012-6354"
var1 = x.find("s")
var2 = x.rfind("b")
var3 = x.capitalize()
var4 = x.title()
var5 = x.upper()
var6 = x.lower()
var7 = x.isdigit()
var8 = x.count("-")
var9 = x.replace("-","")
var10 = x.split()

print(var1)
print(var2)
print(var3)
print(var4)
print(var5)
print(var6)
print(var7)
print(var8)
print(var9)
print(var10)




8
36
Hello customer! your credit card number is 1234-5678-9012-6354
Hello Customer! Your Credit Card Number Is 1234-5678-9012-6354
HELLO CUSTOMER! YOUR CREDIT CARD NUMBER IS 1234-5678-9012-6354
hello customer! your credit card number is 1234-5678-9012-6354
False
3
Hello Customer! Your credit card number is 1234567890126354
['Hello', 'Customer!', 'Your', 'credit', 'card', 'number', 'is', '1234-5678-9012-6354']


## **Task of Strings**

In [ ]:
email = "midhat.kamal@bankalfalah.com"
path="C:/Users/Misbah/Documents/file.txt"


splitTask = path.split("/")
print(f"{splitTask}")

findvalue = email.rfind("@") #rFind used to check last occurence
print(f"The user ID is: {email[0:findvalue]}")

print(f"The domain name is: {email[findvalue+1::]}")

['C:', 'Users', 'Misbah', 'Documents', 'file.txt']
The user ID is: midhat.kamal
The domain name is: bankalfalah.com


## **Validate user input Exercise**

In [ ]:
userName = input("Please enter the username: ")
if len(userName)>12:
  print("The user name should not be more than 12 characters")
elif not userName.find(" ")==-1:
  print("The user name should not contain spaces")
elif not userName.isalpha():
  print("The user name should not contain digits")
else:
  print("Correct username")


Please enter the username: midhat.kamal
The user name should not contain digits


In [ ]:
#Format Specifiers
price1 =3.444
price2=-44
price3=23.5

print(f"price 1 is ${price1:.1f}") #round of to 1 decimal place
print(f"price 2 is ${price2:>10}")
print(f"price 3 is ${price1:}")
print(f"price 3 is ${price1:.1f}")
print(f"price 3 is ${price1:.1f}")
print(f"price 3 is ${price1:.1f}")

price 1 is $3.4
price 2 is $       -44
price 3 is $3.444
price 3 is $3.4
price 3 is $3.4
price 3 is $3.4


Exercise

In [ ]:
productName = "Bat" #input("Enter the product name: ")
quantity = 3 #int(input("Enter the quantity: "))
unitPrice = 100
priceWithTax = float(quantity*unitPrice*0.08)

print(f"{'Product':<15}{'Price':>10} {'Tax (8%)':>15}")
print(f"{productName:<15}{unitPrice:>10.2f}{priceWithTax:>15.2f}")
#print(f"{productName: <10}{quantity: <15} {unitPrice: <10} {priceWithTax: <10}")




Product             Price        Tax (8%)
Bat                100.00          24.00


In [ ]:

#+,-,*,/,**,% Arithmetic
#+=,-=,*=,/=,**=,%= Assignment
#and,or,not
#is,is not
#in, not in
#==,!=,>,<,<=,>= Comparison


#Control flow
#Conditional -if
#loops while,for,nested
#match-case


In [ ]:
#X if condition else Y
num = 6;
print("Greater than 5") if num>5 else print("less than 5")

Greater than 5


In [ ]:
#Python compound interest
#Major conditions = Principle Amount

principle =0

while principle <=0:
  principle = float(input("Enter your principle amount: "))

In [ ]:
for x in range(9): #rows
  for y in range(4): #columns
    print('*',end="/")
  print()

*/*/*/*/
*/*/*/*/
*/*/*/*/
*/*/*/*/
*/*/*/*/
*/*/*/*/
*/*/*/*/
*/*/*/*/
*/*/*/*/


In [ ]:
#Match Case

day=1
match day:
  case 1:
    print("It is Sunday")

It is Sunday


In [ ]:
#List [],Ordered, Mutables/Changeable / no duplicates
#Sets
#Tuples
#Dictionary

# **Functions**

In [7]:
def happy_birthday(name,age):
  print(f"Happy Birthday {name}!")
  print(f"You are {age} years old")


happy_birthday("Midhat",25)

Happy Birthday Midhat!
You are 25 years old


In [8]:
#Positional Arguments
#Example 1 - Order change gives diff output
def happy_birthday(name,age):
  print(f"Happy Birthday {name}")
  print(f"You are {age} years old")



happy_birthday(25,"Midhat")

Happy Birthday 25
You are Midhat years old


###Default Arguments

In [22]:
#Default Arguments

def net_price(price,discount=0,tax=0.05):
  return price*(1-discount)*(1+tax)


print(net_price(500,0.02,0.01)) #All three values changed
print(net_price(500,tax=0.01)) #Only tax is changed, discount remains default

494.9
505.0


###Keyword Arguments

In [15]:
#Keyword Arguments
def hello(greeting,title,first,last):
  print(f"{greeting} {title} {first} {last}")

hello("Hello", title="Ms.", last="Kamal", first="Midhat")
hello("Hello", last="Kamal", first="Midhat", title="Ms.")

Hello Ms. Midhat Kamal
Hello Ms. Midhat Kamal


In [26]:
def get_phone(country,area,first,last):
  return f"{country}{area}{first}{last}"

phoneNo = get_phone(country="+92",area=332,first=456,last=123)
print(phoneNo)

+92332456123


In [31]:
#*args and **kwargs
def add(a,b):
  return a+b



add(1,2,3)

TypeError: add() takes 2 positional arguments but 3 were given

###Arbitrary Arguments

In [39]:
#*args and **kwargs
#*args handles the variable number of positional arguments as a tuple [dont have key]
#*kwargs handles the variable number of keyword arguments as a dictionary
#The * before any argument makes it arbitrary
#The ** before any argument makes it kwargs


def add(*args):
  print(type(args))
  print(args)


add(1,2,3)
add([1,2,3])


def display_name(*args):
  for arg in args:
    print(arg,end=" ")


display_name("Ms.","Midhat","Kamal")



<class 'tuple'>
(1, 2, 3)
<class 'tuple'>
([1, 2, 3],)
Ms. Midhat Kamal 

## args and kwargs

In [43]:
#*args and **kwargs
#*args handles the variable number of positional arguments as a tuple [dont have key]
#*kwargs handles the variable number of keyword arguments as a dictionary
#The * before any argument makes it arbitrary
#The ** before any argument makes it kwargs

#PROBLEM
def print_address(**x):
  print(type(x))
  print()

print_address(street="C-5",city="Karachi",province="Sindh")


print("Solution to above problem using **kwargs: ")
#SOLUTION
def print_addressNew(**x):
  for key in x.keys():  #for values in x.values():   #for item in x.items():
    print(f"{key}")


print_addressNew(street="C-5",city="Karachi",province="Sindh")


<class 'dict'>

Solution to above problem using **kwargs: 
street
city
province


In [55]:
def shipping_label(*args,**kwargs):
  print("problem using args")
  for arg in args:
    print(arg,end="")

  print()

  print("problem using args")
  for key,value in kwargs.items():
    print(f"{key}: {value}")


shipping_label("Ms.","Midhat",street="Gulshan")


problem using args
Ms.Midhat
problem using args
street: Gulshan


In [60]:
def shipping_label(*args,**kwargs):
  print("problem using args")
  for arg in args:
    print(arg,end=" ")
  print("problem using args")
  print(f"{kwargs.get('street')}")
  print(f"{kwargs.get('zip')}")
  print(f"{kwargs.get('province')}")



shipping_label("Ms.","Midhat",street="Gulshan",zip='715300',province="Sindh")

problem using args
Ms. Midhat problem using args
Gulshan
715300
Sindh


In [74]:
#Task 1: In restaurant, when you order food, you typically specify the main course and the drink by their position in the order

def order_food(maincourse,drink):
  print(f"You have ordered {maincourse} with complementary {drink}")

order_food("Alfredo Pasta","Apple Fiz")
print()
order_food("Parmesan Chicken","Cherry")




You have ordered Alfredo Pasta with complementary Apple Fiz

You have ordered Parmesan Chicken with complementary Cherry


In [73]:
#Task 2: Default Arguments
def flight_booking(seatClass="economy"):
  print(f"You have booked flight in {seatClass} class")

flight_booking()
print()
flight_booking("first")

You have booked flight in economy class

You have booked flight in first class


In [76]:
#Task 3:
def pizza_specification(size,topping,crust="Thin"):
  print("Please find your pizza specifications below: ")
  print(f"{size}")
  print(f"You did not select any crust; therefore, your crust is by-default {crust}") if crust=="Thin" else print(f"{crust}")
  print(f"{topping}")

pizza_specification(size="Small",crust="Stuffed",topping="Cheese")
print()
pizza_specification(size="Large",topping="Ranch Sauce")

Please find your pizza specifications below: 
Small
Stuffed
Cheese

Please find your pizza specifications below: 
Large
You did not select any crust; therefore, your crust is by-default Thin
Ranch Sauce


## **NUMPY**

In [ ]:
#Numpy (Numerical python)
#pandas -> dataframe - showing data

In [78]:
import numpy as np

In [79]:
array_1d = np.array([1,2,3,4,5,6])
print("1D Array: ", type(array_1d))

1D Array:  <class 'numpy.ndarray'>


In [82]:
array_2d = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])
print("2D Array: ", array_2d)

2D Array:  [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [81]:
zeros_aray = np.ones((2,3))
print("zeros Array: ", zeros_aray)

1D Array:  [[1. 1. 1.]
 [1. 1. 1.]]


In [84]:
#Creating an array with a range of numbers 0-10 with step size 2
range_array = np.arange(0,10,2)
print("Range arrray: ", range_array)

Range arrray:  [0 2 4 6 8]


In [87]:
#array of particular value
p_array = np.full((5,4),5)
print(p_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [88]:
lin_array = np.linspace(10,30,5)
print(lin_array)

[10. 15. 20. 25. 30.]


In [95]:
arrange_array = np.arange(10,30,5)
print(arrange_array)

[10 15 20 25]


In [93]:
a=np.random.random((3,4))
print(a)

[[0.16148405 0.62333867 0.94444739 0.74077005]
 [0.80948098 0.64876396 0.41398428 0.71680406]
 [0.42174514 0.03070786 0.22459565 0.15424723]]


In [92]:
a=np.random.randint(10,100,(3,5)) #3 rows 5 columns
print(a)

[[51 46 17 93 16]
 [82 75 88 48 29]
 [25 12 62 53 88]]


In [96]:
print(a.shape) #number of rows and columns

(3, 4)


In [97]:
print(a.ndim) #number of square brackets

2


In [98]:
print(a.size)

12


In [99]:
print(a.dtype)

float64


In [103]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

print()

b=a.reshape(3,2)
print(b)
print(b.shape)

[[8 6 0]
 [4 7 5]]
(2, 3)

[[8 6]
 [0 4]
 [7 5]]
(3, 2)


In [ ]:
lists1 = [1,2,3,5,6,7]
print(lists1)
type()


np_array = np.asarray(lists1)


In [112]:
a = np.random.randint(0,10,(2,3))
b = np.random.randint(0,10,(2,3))
np.concatenate((a,b))

array([[4, 5, 6],
       [0, 3, 5],
       [1, 4, 2],
       [7, 1, 9]])

In [109]:
#Add/Subtract/Divide

print(np.add(a,b))

[[15  7  5]
 [ 6  8 11]]


In [104]:
c = a+5
print(c)

[[13 11  5]
 [ 9 12 10]]


In [105]:
np.mean(a)

5.0

In [113]:
from time import process_time

python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time-start_time)

0.0013874200000003611
